language: python
python:
  -3.8



addons:
  apt:
    packages:
      - python3
before_install:
- sudo apt-get update
- sudo apt-get install python3

before_script: pip install spotipy

# install:

script:
  -python3 pruebas_unitarias.py
  -python3 prueba_integracion.py